<?php
$productNames = $this->getProductname();
$productImages = $this->getProductimage();
?>
<?php if ($productNames): ?>
    <table>
        <tr>
            <th>
                <?php echo Mage::helper('abandonedcarts')->__('Product Image'); ?>
            </th>
            <th>
                <?php echo Mage::helper('abandonedcarts')->__('Product Name'); ?>
            </th>
        </tr>
        <?php foreach($productNames as $i => $name): ?>
            <tr>
                <td>
                    <?php if ($productImages[$i]): ?>
                        <img src="<?php echo $productImages[$i]; ?>" alt="<?php echo $name; ?>" />
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $name; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
